CREATE TABLE PRODUCTO(
    ID_PRODUCTO NUMBER,
    NOMBRE NVARCHAR2(100),
    CATEGORIA_ID NUMBER, --1.TECNOLOGIA --2.HOGAR 3. ROPA 4. JUGUETERIA 5.FARMACIA
    PRECIO NUMBER,
    STOCK NUMBER,
    MARCA NVARCHAR2(100),
    CONSTRAINT PRODUCTO_PK PRIMARY KEY(ID_PRODUCTO)
);

INSERT INTO PRODUCTO VALUES(1, 'LAPTOP LENOVO', 1,118500, 10, 'LENOVO');
INSERT INTO PRODUCTO VALUES(2, NULL, NULL ,NULL, NULL, NULL);
INSERT INTO PRODUCTO VALUES(3, 'PLAYERA NIKE',3,  950, 25, 'NIKE');
INSERT INTO PRODUCTO VALUES(4, 'TENIS ADIDAS', 3, 1200, 15, 'ADIDAS');
INSERT INTO PRODUCTO VALUES(5, 'SUDADERA PUMA', 3, 850, 10, 'PUMA');
INSERT INTO PRODUCTO VALUES(6, 'PANTALON',3,400,50,'LEVIS');
INSERT INTO PRODUCTO VALUES(7, 'AUDIFONO',1,800,100,'BEATS SOUND');
INSERT INTO PRODUCTO VALUES (8, 'JUEGO DE MESA', 4,400, 4, 'FOTORAMA');
INSERT INTO PRODUCTO VALUES (9, 'XBOX', 1,25, 500, 'MICROSOFT');


/*
MOSTRAR EL NOMBRE DE LA CATEGORIA USANDO CASE 
CLASIFICAR PRODUCTOS SEGUN EL PRECIO (CARO, MEDIO, ECONOMICO)
CLASIFICAR PRODUCTOS POR DISPONIBILIDAD DE STOCK(AGOTADO, BAJO STOCK, INSUFICIENTE)
MENSAJE COMPUESTO USANDO CASE Y CONCATENACION PARA STOCK
USAR CASE PARA CLASIFICAR POR PRECIO Y POR STOCK SI ES COSTOSO Y SI ESTA DISPONIBLE


*/

--1MOSTRAR EL NOMBRE DE LA CATEGORIA USANDO CASE 
SELECT 
  ID_PRODUCTO,
  NOMBRE,
  CATEGORIA_ID,
(
  CASE CATEGORIA_ID
    WHEN 1 THEN 'TECNOLOGÍA'
    WHEN 2 THEN 'HOGAR'
    WHEN 3 THEN 'ROPA'
    WHEN 4 THEN 'JUGUETERÍA'
    WHEN 5 THEN 'FARMACIA'
    ELSE 'SIN CATEGORÍA'
  END 
)AS NOMBRE_CATEGORIA FROM PRODUCTO;

--2 CLASIFICAR PRODUCTOS SEGUN EL PRECIO (CARO, MEDIO, ECONOMICO)
SELECT 
  ID_PRODUCTO,
  NOMBRE,
  PRECIO,
(
  CASE
    WHEN PRECIO >= 1000 THEN 'CARO'
    WHEN PRECIO < 999  AND PRECIO >=400 THEN 'MEDIO'
    WHEN PRECIO < 300  THEN 'ECONOMICO'
    ELSE 'SIN PRECIO'
  END 
)AS CLASIFICACION_PRECIO FROM PRODUCTO;

--3 CLASIFICAR PRODUCTOS POR DISPONIBILIDAD DE STOCK(AGOTADO, BAJO STOCK, INSUFICIENTE)
SELECT 
  ID_PRODUCTO,
  NOMBRE,
  STOCK,
(
  CASE
    WHEN STOCK = 0 THEN 'AGOTADO'
    WHEN STOCK BETWEEN 1 AND 5 THEN 'INSUFICIENTE'
    WHEN STOCK BETWEEN 6 AND 15 THEN 'BAJO STOCK'
    WHEN STOCK BETWEEN 16 AND 49 THEN 'STOCK ADECUADO'
    WHEN STOCK BETWEEN 50 AND 1000 THEN 'STOCK ABUNDANTE'
    ELSE 'STOCK NO DISPONIBLE'
  END 
)AS DISPONIBILIDAD FROM PRODUCTO;

--4 MENSAJE COMPUESTO USANDO CASE Y CONCATENACION PARA STOCK
SELECT 
  ID_PRODUCTO,
  NOMBRE,
  STOCK,
  'EL PRODUCTO "' || NOMBRE || '" TIENE UN STOCK DE: ' || 
(
  CASE
    WHEN STOCK = 0 THEN '0 UNIDADES: AGOTADO'
    WHEN STOCK < 15 THEN STOCK || ' UNIDADES: BAJO STOCK'
    ELSE STOCK || ' UNIDADES: DISPONIBLES'
  END 
)AS UNIDADES FROM PRODUCTO;

--5 USAR CASE PARA CLASIFICAR POR PRECIO Y POR STOCK SI ES COSTOSO Y SI ESTA DISPONIBLE
SELECT 
  ID_PRODUCTO,
  NOMBRE,
  PRECIO,
  STOCK,
(
  CASE
    WHEN PRECIO > 1000 AND STOCK >= 10 THEN 'COSTOSO Y DISPONIBLE'
    WHEN PRECIO <= 1000 AND STOCK <= 10 THEN 'COSTOSO Y POCO STOCK'
    WHEN PRECIO < 1000 AND STOCK >= 10 THEN 'ECONOMICO Y DISPONIBLE'
    WHEN PRECIO <= 0 AND STOCK <= 5 THEN 'ECONOMICO Y POCO STOCK'
    /*WHEN PRECIO < 500 AND STOCK >= 0 THEN 'ECONÓMICO PERO CON POCO STOCK'*/
    ELSE 'PRECIO Y PRODUCTO NO DISPONIBLE'
  END 
)AS CLASIFICACION_GENERAL FROM PRODUCTO;

