
CREATE TABLE EMPRESA(
    ID_EMPRESA NUMBER,
    NOMBRE NVARCHAR2(100),
    RUBRO NVARCHAR2(100),
    UBICACION NVARCHAR2(100),
    CONSTRAINT EMPRESA_PK PRIMARY KEY(ID_EMPRESA)
);

INSERT INTO EMPRESA VALUES(1, 'TACHCOPR', 'TECNOLOGIA', 'CIUDAD DE MEXICO');
INSERT INTO EMPRESA VALUES(2, 'BOIVIDA', NULL, NULL);
INSERT INTO EMPRESA VALUES(3, 'FARMAVIDA', 'FARMACIA', 'MONTERREY');
INSERT INTO EMPRESA VALUES(4, 'JUGUEFANTASY', 'JUGUETERÍA', 'PUEBLA');
INSERT INTO EMPRESA VALUES(5, 'FFT', 'CONTRATISTA', 'PUEBLA');
INSERT INTO EMPRESA VALUES(6, 'AUTOTEK', 'AUTOPARTES', 'TOLUCA');
INSERT INTO EMPRESA VALUES(7, 'INTEL', 'TECNOLOGÍA ', 'MONTERREY');
INSERT INTO EMPRESA VALUES(8, 'HP', 'TECNOLOGÍA ', 'JALISCO');

SELECT * FROM EMPRESA;

CREATE TABLE TRABAJADOR(
    ID_TRABAJADOR NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    PUESTO NVARCHAR2(100),
    SUELDO NUMBER,
    EMPRESA_ID NUMBER,
    CONSTRAINT TRABAJADOR_PK PRIMARY KEY(ID_TRABAJADOR),
    CONSTRAINT EMPRESA_FK FOREIGN KEY(EMPRESA_ID) REFERENCES EMPRESA(ID_EMPRESA)
);

INSERT INTO TRABAJADOR VALUES (1, 'JUAN', 'PEREZ', 'INGENIERO', 25000, 1);
INSERT INTO TRABAJADOR VALUES (2, 'LILI', 'DIAZ', 'BIOLOGO', 2200, NULL);
INSERT INTO TRABAJADOR VALUES (3, 'CARLOS', 'RAMÍREZ', 'CONTADOR', 18000, 5);
INSERT INTO TRABAJADOR VALUES (4, 'LUISA', 'FERNÁNDEZ', 'MARKETING', 20000, 6);
INSERT INTO TRABAJADOR VALUES (5, 'JORGE', 'CAMPOS', 'DISEÑADOR', 35000, 3);
INSERT INTO TRABAJADOR VALUES (6, 'HUGO', 'MORALES', 'INGENIERIA', 32000, 2);
INSERT INTO TRABAJADOR VALUES(7,'ALBERTO', 'MORALES', 'SOLDADOR', 18000,2);
INSERT INTO TRABAJADOR VALUES(8,'DANIEL', 'MARTINEZ', 'ABOGADO', 28000,4);

/*
MOSTRAR TRABAJADORES CON UNA EMPRESA 
TODOS LOS TRABAJADORES AUNQUE NO TENGAN EMPRESA
TODOS LOS TRABAJADORES SIN EMPRESA
TODAS LAS EMPRESAS AUNQUE NO TENGAN TRABAJADORES
TODAS LAS EMPRESAS SIN TRABAJADORES
TODAS LAS EMPRESAS Y TODOS LOS TRABJADORES 
TODAS LAS EMPRESAS SIN TRABAJADORES Y TODOS LOS TRABAJADORES SIN EMPRESA


*/

--1.MOSTRAR TRABAJADORES CON UNA EMPRESA  
SELECT * FROM TRABAJADOR T
INNER JOIN EMPRESA E 
ON T.EMPRESA_ID = E.ID_EMPRESA;

--2. TODOS LOS TRABAJADORES AUNQUE NO TENGAN EMPRESA
SELECT  * FROM TRABAJADOR T
LEFT JOIN EMPRESA E 
ON T.EMPRESA_ID = E.ID_EMPRESA;

--3. TODOS LOS TRABAJADORES SIN EMPRESA
SELECT * FROM TRABAJADOR T
LEFT JOIN EMPRESA E 
ON T.EMPRESA_ID = E.ID_EMPRESA
WHERE E.ID_EMPRESA IS NULL;

--4 TODAS LAS EMPRESAS AUNQUE NO TENGAN TRABAJADORES
SELECT 
  E.ID_EMPRESA,
  E.NOMBRE AS NOMBRE_EMPRESA,
  T.ID_TRABAJADOR,
  T.NOMBRE AS NOMBRE_TRABAJADOR
FROM EMPRESA E
LEFT JOIN TRABAJADOR T 
ON E.ID_EMPRESA = T.EMPRESA_ID;

--5- TODAS LAS EMPRESAS AUNQUE NO TENGAN TRABAJADORES
SELECT  * FROM EMPRESA E
LEFT JOIN TRABAJADOR T 
ON E.ID_EMPRESA = T.EMPRESA_ID
WHERE T.ID_TRABAJADOR IS NULL;

--6. TODAS LAS EMPRESAS Y TODOS LOS TRABAJADORES
SELECT * FROM EMPRESA E
LEFT JOIN TRABAJADOR T 
ON E.ID_EMPRESA = T.EMPRESA_ID;


--7 TODAS LAS EMPRESAS SIN TRABAJADORES Y TODOS LOS TRABAJADORES SIN EMPRESA
SELECT * FROM EMPRESA E
FULL OUTER JOIN TRABAJADOR T 
ON E.ID_EMPRESA = T.EMPRESA_ID
WHERE E.ID_EMPRESA IS NULL 
OR T.ID_TRABAJADOR IS NULL;