

CREATE TABLE TALLER(
    ID_TALLER NUMBER,
    TITULO NVARCHAR2(100),
    NIVEL NUMBER, --1.BASICO, 2INTERMEDIO, 3. AVANZADO
    DURACION_HRS NUMBER,
    INSTRUCTOR NUMBER, --1ALMA, 2. CECILIA, 3. BRUNO, 4. DAVID, 5. ESTELA, 6. FERNANDO
    CONSTRAINT TALLER_PK PRIMARY KEY(ID_TALLER)
);

INSERT INTO TALLER VALUES(1, 'TALLER DE ORATORIA', 2,10,1);
INSERT INTO TALLER VALUES(2, 'INTRODUCCION A PYTHON', 0,20,0);
INSERT INTO TALLER VALUES(3, 'TALLER DE PROGRAMACIÓN', 3, 20, 2);
INSERT INTO TALLER VALUES(4, 'TALLER DE PRIMEROS AUXILIOS', 3, 15, 3);
INSERT INTO TALLER VALUES(5,'TALLER DE PINTURA',2,15,3);
INSERT INTO TALLER VALUES(6,'TALLER DE BAILE',3,40,5);
INSERT INTO TALLER VALUES (7,'TALLER DE MATERIALES', 3, 40, 5);
INSERT INTO TALLER VALUES (8,'TALLER DE COCINA', 1, 25, 3);

SELECT * FROM TALLER;

CREATE TABLE PARTICIPANTE(
    ID_PARTICIPANTE NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    OCUPACION NUMBER, --1ESTUDIANTE 2.DOCENTE,,3. EMPRENDEDOR, 4.PROFESIONAL INDEP, 5. EMPLEADO
    TALLER_ID NUMBER,
    CONSTRAINT PARTICIPANTE_PK PRIMARY KEY(ID_PARTICIPANTE),
    CONSTRAINT TALLER_FK FOREIGN KEY(TALLER_ID) REFERENCES TALLER(ID_TALLER)
);

INSERT INTO PARTICIPANTE VALUES(1, 'LUISA', 'CARRILLO', 24,1,1);
INSERT INTO PARTICIPANTE VALUES(2, 'OMAR', NULL, 32,0,NULL);
INSERT INTO PARTICIPANTE VALUES(3,'DIANA', 'VAZQUEZ',21,1,7);
INSERT INTO PARTICIPANTE VALUES(4,'VIVIAN', 'CARMONA',26,5,2);
INSERT INTO PARTICIPANTE VALUES(5, 'ARTURO', 'SANCHEZ', 29,4,4);
INSERT INTO PARTICIPANTE VALUES(6, 'FERNANDO', 'ROSAS', 31,5,6);
INSERT INTO PARTICIPANTE VALUES(7, 'ANA', 'RODRÍGUEZ', 22, 3, 3);
INSERT INTO PARTICIPANTE VALUES(8, 'JORGE', 'SALGADO', 28, 4, 5);
INSERT INTO PARTICIPANTE VALUES(2, 'OMAR', NULL, 32, NULL, NULL);

SELECT * FROM PARTICIPANTE;

/*
    1.MOSTRAR LOS REGISTROS DE LOS PARTICIPANTES JUNTO AL NOMBRE DEL TALLER USANDO CLASE PARA MOSTRAR EL NOMBRE 
    DEL INSTRUCTOR Y LA OCUPACION
    2. CONTAR CUANTOS PARTICIPANTES HAY POR TALLER
    3. MOSTRAR LOS TALLERES CON MAYOR DURACION Y CONCATENAR LA PALABRA "HORAS" AL FINAL
    4.MOSTRAR EL NOMBRE DEL INSTRUCTOR QUE IMPARTE MAS TALLERES
    5. MOSTRAR EL TODOS LOS INSTRUCTOR Y LA CANTIDAD DE TALLERES QUE IMPARTEN
    6. ORDENAR LOS TALLERES ALFABETICAMENTE POR TITULO Y LUEGO POR DURACION DE MAYOR A MENOR
    7.ORDENAR A LOS PARTICIPANTES POR NOMBRE Y POR EDAD
    8. MOSTRAR EL TOTAL DE HORAS QUE TOMARA CADA PARTICIPANTE SEGUN SU TALLER
    9. MOSTRAR EL PARTICIPANTE QUE NO TIENE TALLER ASIGNADO, JUNTO CON SU CLASE DE OCUPACION
    10. MOSTRAR LOS TALLERES QUE NO HAN SIDO ASIGNADOS A NINGUN PARTICIPANTE Y SU CLASE DE INSTRUCTOR Y DE NIVEL
    11. MOSTRAR EL DETALLE DE CADA PARTICIPANTE CON LOS DATOS DEL TALLER AL QUE ASISTIRA USANDO CASE Y PIPES
    (EL PARTICIPANTE: JORGE LUNA DE 26 AÑOS Y QUE SE DEDICA A SER: ESTUDIANTE TOMA EL TALLER DE CATEGORIA QUE IMPARTE EL INSTRUCTOR(A)
    ALNA EB EL NIVEL MEDIO CON UNA DURACION DE 10 HORAS)
*/

--1.MOSTRAR LOS REGISTROS DE LOS PARTICIPANTES JUNTO AL NOMBRE DEL TALLER USANDO CLASE PARA MOSTRAR EL NOMBRE DEL INSTRUCTOR Y LA OCUPACION

SELECT 
    ID_PARTICIPANTE,
    NOMBRE,
    APELLIDO,
    EDAD,
    TITULO AS NOMBRE_TALLER,
    CASE INSTRUCTOR
        WHEN 1 THEN 'ALMA'
        WHEN 2 THEN 'CECILIA'
        WHEN 3 THEN 'BRUNO'
        WHEN 4 THEN 'DAVID'
        WHEN 5 THEN 'ESTELA'
        WHEN 6 THEN 'FERNANDO'
        ELSE 'NO ASIGNADO'
    END AS NOMBRE_INSTRUCTOR,
    CASE OCUPACION
        WHEN 1 THEN 'ESTUDIANTE'
        WHEN 2 THEN 'DOCENTE'
        WHEN 3 THEN 'EMPRENDEDOR'
        WHEN 4 THEN 'PROFESIONAL INDEP'
        WHEN 5 THEN 'EMPLEADO'
        ELSE 'NO DEFINIDA'
    END AS OCUPACION
FROM PARTICIPANTE P
INNER JOIN TALLER T 
ON P.TALLER_ID = T.ID_TALLER;

--2. CONTAR CUANTOS PARTICIPANTES HAY POR TALLER
SELECT 
    TITULO,
    COUNT(P.ID_PARTICIPANTE) AS CANTIDAD_PARTICIPANTES
FROM TALLER T
LEFT JOIN PARTICIPANTE P ON T.ID_TALLER = P.TALLER_ID
GROUP BY T.TITULO;

-- 3. MOSTRAR LOS TALLERES CON MAYOR DURACION Y CONCATENAR LA PALABRA "HORAS" AL FINAL

SELECT 
    TITULO,
    DURACION_HRS || ' HORAS' AS DURACION
FROM TALLER
WHERE DURACION_HRS = (SELECT MAX(DURACION_HRS) FROM TALLER);

--4.MOSTRAR EL NOMBRE DEL INSTRUCTOR QUE IMPARTE MAS TALLERES
SELECT 
    CASE INSTRUCTOR
        WHEN 1 THEN 'ALMA'
        WHEN 2 THEN 'CECILIA'
        WHEN 3 THEN 'BRUNO'
        WHEN 4 THEN 'DAVID'
        WHEN 5 THEN 'ESTELA'
        WHEN 6 THEN 'FERNANDO'
    END AS INSTRUCTOR,
    COUNT(*) AS TOTAL_TALLERES
FROM TALLER
GROUP BY INSTRUCTOR
ORDER BY TOTAL_TALLERES DESC
FETCH FIRST 1 ROWS ONLY;

--5. MOSTRAR EL TODOS LOS INSTRUCTOR Y LA CANTIDAD DE TALLERES QUE IMPARTEN
SELECT 
    CASE INSTRUCTOR
        WHEN 1 THEN 'ALMA'
        WHEN 2 THEN 'CECILIA'
        WHEN 3 THEN 'BRUNO'
        WHEN 4 THEN 'DAVID'
        WHEN 5 THEN 'ESTELA'
        WHEN 6 THEN 'FERNANDO'
    END AS INSTRUCTOR,
    COUNT(*) AS TOTAL_TALLERES
FROM TALLER
GROUP BY INSTRUCTOR;

--6. ORDENAR LOS TALLERES ALFABETICAMENTE POR TITULO Y LUEGO POR DURACION DE MAYOR A MENOR
SELECT * FROM TALLER
ORDER BY TITULO ASC, DURACION_HRS DESC;

--7.ORDENAR A LOS PARTICIPANTES POR NOMBRE Y POR EDAD
SELECT * FROM PARTICIPANTE
ORDER BY NOMBRE ASC, EDAD ASC;

--8. MOSTRAR EL TOTAL DE HORAS QUE TOMARA CADA PARTICIPANTE SEGUN SU TALLER
SELECT 
    ID_PARTICIPANTE,
    NOMBRE,
    APELLIDO,
    EDAD,
    TITULO,
    DURACION_HRS AS HORAS_TALLER
FROM PARTICIPANTE P
INNER JOIN TALLER T ON P.TALLER_ID = T.ID_TALLER;

-- 9. MOSTRAR EL PARTICIPANTE QUE NO TIENE TALLER ASIGNADO, JUNTO CON SU CLASE DE OCUPACION
SELECT 
    ID_PARTICIPANTE,
    NOMBRE,
    APELLIDO,
    EDAD,
    CASE OCUPACION
        WHEN 1 THEN 'ESTUDIANTE'
        WHEN 2 THEN 'DOCENTE'
        WHEN 3 THEN 'EMPRENDEDOR'
        WHEN 4 THEN 'PROFESIONAL INDEP'
        WHEN 5 THEN 'EMPLEADO'
        ELSE 'NO DEFINIDA'
    END AS OCUPACION
FROM PARTICIPANTE P
WHERE P.TALLER_ID IS NULL;

--10. MOSTRAR LOS TALLERES QUE NO HAN SIDO ASIGNADOS A NINGUN PARTICIPANTE Y SU CLASE DE INSTRUCTOR Y DE NIVEL
SELECT 
    TITULO,
    CASE INSTRUCTOR
        WHEN 1 THEN 'ALMA'
        WHEN 2 THEN 'CECILIA'
        WHEN 3 THEN 'BRUNO'
        WHEN 4 THEN 'DAVID'
        WHEN 5 THEN 'ESTELA'
        WHEN 6 THEN 'FERNANDO'
        ELSE 'NO DEFINIDO'
    END AS INSTRUCTOR,
    CASE NIVEL
        WHEN 1 THEN 'BÁSICO'
        WHEN 2 THEN 'INTERMEDIO'
        WHEN 3 THEN 'AVANZADO'
        ELSE 'NO DEFINIDO'
    END AS NIVEL
FROM TALLER T
LEFT JOIN PARTICIPANTE P 
ON T.ID_TALLER = P.TALLER_ID
WHERE P.ID_PARTICIPANTE IS NULL;

--11. MOSTRAR EL DETALLE DE CADA PARTICIPANTE CON LOS DATOS DEL TALLER AL QUE ASISTIRA USANDO CASE Y PIPES
SELECT 
    'EL PARTICIPANTE: ' || NOMBRE || ' ' || NVL(APELLIDO, '') ||
    ' DE ' || EDAD || ' AÑOS Y QUE SE DEDICA A: ' ||
    CASE OCUPACION
        WHEN 1 THEN 'ESTUDIANTE'
        WHEN 2 THEN 'DOCENTE'
        WHEN 3 THEN 'EMPRENDEDOR'
        WHEN 4 THEN 'PROFESIONAL INDEP'
        WHEN 5 THEN 'EMPLEADO'
        ELSE 'NO DEFINIDA'
    END ||
    ' TOMA EL TALLER DE ' || TITULO ||
    ' QUE IMPARTE EL INSTRUCTOR(A) ' ||
    CASE INSTRUCTOR
        WHEN 1 THEN 'ALMA'
        WHEN 2 THEN 'CECILIA'
        WHEN 3 THEN 'BRUNO'
        WHEN 4 THEN 'DAVID'
        WHEN 5 THEN 'ESTELA'
        WHEN 6 THEN 'FERNANDO'
        ELSE 'NO DEFINIDO'
    END ||
    ' EN EL NIVEL ' ||
    CASE NIVEL
        WHEN 1 THEN 'BÁSICO'
        WHEN 2 THEN 'INTERMEDIO'
        WHEN 3 THEN 'AVANZADO'
        ELSE 'NO DEFINIDO'
    END ||
    ' CON UNA DURACION DE ' || DURACION_HRS || ' HORAS' AS DETALLE
FROM PARTICIPANTE P
INNER JOIN TALLER T 
ON P.TALLER_ID = T.ID_TALLER;







