--uso de DML PARA INSERTAR 

INSERT INTO EMPLEADO VALUES(1, 'MAURICIO', 'SANCHES', 26, 'ABOGADO', 'DEPARTAMENTO PENAL');

INSERT INTO EMPLEADO VALUES(2,'LILIANA', 'ZAMORA', 23, 'AUXILIAR', 'CONTABILIDAD');

INSERT INTO EMPLEADO VALUES(5,'VANIA', 'TAPIA', 24, 'ASISTENTE', 'RH');
INSERT INTO EMPLEADO VALUES(6,'JAQUELINE', 'HERNANDEZ', 20, 'PROGRAMADOR', 'SISTEMAS');
INSERT INTO EMPELADO VALUES(3,'MARIO', 'DOMINGUES', 30, 'DOCTOR', 'ONCOLOGIA');
INSERT INTO EMPELADO VALUES(7,'JESUS', 'HUERTA', 21, 'AUXILIAR','CONTABILIDAD');

INSERT INTO EMPLEADO VALUES(10,'CARLOS', 'MATUS', 25, 'AUXILIAR', 'CONTABILIDAD');
INSERT INTO EMPLEADO VALUES(9,'ANA', 'LOPEZ', 27, 'SOPORTE', 'TI');

SELECT * FROM EMPLEADO;

--FUNCIONES 

--MODIFICAR O CAMBIAR EL NOMBRE DE LA COLUMNA

ALTER TABLE EMPLEADO RENAME COLUMN APP TO APPELLIDO;

--DML ACTUALIZAR 
UPDATE EMPLEADO SET NOMBRE = 'LILI' WHERE ID_EMPLEADO = 2;

--ORDER BY

SELECT * FROM EMPLEADO ORDER BY EDAD ASC;

SELECT * FROM EMPLEADO ORDER BY EDAD DESC;

--BUSQUEDA DE INFORMACION CON CARACTERES EN ESPECIFICO
--BUSCAR EMPLEADO CON LA INICIAL A

SELECT * FROM EMPLEADO WHERE NOMBRE LIKE'A%';
--BUSCAR EMPLEADO QUE CONTENGA LA I
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE'%I%';
--BUSCAR EMPLEADO QUE FINALICE CON LA O
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE'%O';

--BUSCAR EMPLEADO QUE SU NOMBRE NO SEA NULL
SELECT * FROM EMPLEADO WHERE NOMBRE IS NOT NULL;

SELECT 5 + 5 AS SUMA FROM DUAL;

SELECT LENGTH('ESTA ES UNA VADENA DE PRUEBA PARA EL USO DE LA FUNCION') AS TAMINIO FROM DUAL;

--BUSCAR CON MAS CONDICIONES
--BUSCAR EMPLEADO MAYOR A 25

SELECT * FROM EMPLEADO WHERE EDAD >25;
--MENORES 26
SELECT * FROM EMPLEADO WHERE EDAD <26;
--MAYORES 24 Y MENORES 28
SELECT * FROM EMPLEADO WHERE EDAD >24 AND EDAD<27;
--RANGO BETWEENN

SELECT * FROM EMPLEADO WHERE EDAD BETWEEN 24 AND 27;

--BUSCAR EMPLEADOS CON EL ID=1, 3, 5

SELECT * FROM EMPLEADO WHERE ID_EMPLEADO = 1 OR ID_EMPLEADO = 5 OR ID_EMPLEADO =9;
--FUNCION IN
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO IN(1,5,9);

--USO DE LA FUNCION BY Y COUNT
SELECT  DEPARTAMENTO FROM EMPLEADO GROUP BY DEPARTAMENTO;
SELECT DEPARTAMENTO, COUNT(ID_EMPLEADO) AS NO_EMPLEADO FROM EMPLEADO WHERE DEPARTAMENTO IS NOT NULL GROUP BY DEPARTAMENTO;

--CONTAR EMPLEADOS QUE TENGAN +25
SELECT COUNT(ID_EMPLEADO) AS TOTAL_EMPLEADOS FROM EMPLEADO WHERE EDAD>25;

--FUNCION DE AGREGACION SUM
SELECT SUM(EDAD) AS SUMA_EDADES FROM EMPLEADO WHERE APPELLIDO LIKE '%Z';
--FUNCION AGREGACION MAX
SELECT MAX(EDAD) AS EDAD_MINIMA FROM EMPLEADO;
--FUNCION AGREGACION MIN
SELECT MIN(EDAD) AS EDAD_MINIMA FROM EMPLEADO;

--FUNCION DE AGREGACION AVG
SELECT AVG(EDAD) AS EDAD_PROMEDIO FROM EMPLEADO;
--USO DE LA FUNCION ROUND
SELECT ROUND(AVG(EDAD), 0) AS PROMEDIO_EDAD FROM EMPLEADO;
--USO DE TU CHAR CON FORMATO
SELECT TO_CHAR(AVG(EDAD), 'FM999.0') AS PROMEDIO_EDAD FROM EMPLEADO WHERE EDAD<29;

--FUNCION CONCAT

SELECT CONCAT(CONCAT(CONCAT(CONCAT('EL EMPLEADO:', ''), NOMBRE), ' '), APPELLIDO) AS DETALLE  FROM EMPLEADO;

--USO DE PIPE O BARRA VERTICAL-> ||
SELECT 'EL EMPLEADO(A): ' ||NOMBRE || ' ' || APPELLIDO || ' DE EDAD: ' ||EDAD ||' AÑOS, TRABAJA EN EL DEPARTAMENTO DE: '||DEPARTAMENTO || ' COMO ' || PUESTO
AS DETALLE FROM EMPLEADO;

--SUBCONSULTA

SELECT * FROM EMPLEADO WHERE
EDAD =(
        SELECT MAX(EDAD)
        FROM EMPLEADO
        WHERE DEPARTAMENTO = ('CONTABILIDAD')
);

SELECT * FROM EMPLEADO WHERE
EDAD =(
        SELECT MIN(EDAD)
        FROM EMPLEADO
        WHERE DEPARTAMENTO = ('CONTABILIDAD')
);












