--EJERCICIO DE JOINS 
--CREAR DDL LAS ENTIDADES DE PADRE E HIJO

CREATE TABLE PADRE(
    ID_PADRE NUMBER, 
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    TRABAJO NVARCHAR2(100),
    CONSTRAINT PADRE_PK PRIMARY KEY(ID_PADRE)
);

INSERT INTO PADRE VALUES(1, 'RICARDO', 'GONZALES', 52, 'DOCENTE');
INSERT INTO PADRE VALUES(2, NULL, 'HUERTA', 0, NULL);
INSERT INTO PADRE VALUES(3, 'MARÍA', 'PÉREZ', 48, 'ENFERMERA');
INSERT INTO PADRE VALUES(4, 'LUIS', 'MARTÍNEZ', 55, 'INGENIERO');
INSERT INTO PADRE VALUES(5, 'ANA', 'LOPEZ', 50, 'ABOGADA');
INSERT INTO PADRE VALUES(6, 'MIGUEL', 'MARTINEZ',51, 'PINTOR');
INSERT INTO PADRE VALUES(7, 'ABEL', 'SANTIAGO',56, 'AGRICULTOR');
INSERT INTO PADRE VALUES(8, 'LUIS', 'JIMENEZ',48, 'ARQUITECTO');
INSERT INTO PADRE VALUES (9, 'JESUS', 'SANCHEZ', 43, 'DOCTOR');
INSERT INTO PADRE VALUES (10, 'ARTURO', 'ROJO', 29, 'MAESTRO');
INSERT INTO PADRE VALUES (11, 'JAREDT', 'TORRES', 32, 'PLOMERO');

SELECT * FROM PADRE;

CREATE TABLE HIJO(
    ID_HIJO NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    HOBBIE NVARCHAR2(100),
    PADRE_ID NUMBER, 
    CONSTRAINT HIJO_PK PRIMARY KEY(ID_HIJO),
    CONSTRAINT PADRE_FK FOREIGN KEY(PADRE_ID) REFERENCES PADRE(ID_PADRE)
);

INSERT INTO HIJO VALUES(1, 'ABEL', 'GONZALES',12, 'JUGAR FUTBOL', 1);
INSERT INTO HIJO VALUES(2, 'DANIELA', NULL, 20, NULL, NULL);
INSERT INTO HIJO VALUES(3, 'LUCÍA', 'PÉREZ', 10, 'DIBUJAR', 3);
INSERT INTO HIJO VALUES(4, 'MATEO', 'MARTÍNEZ', 14, 'LEER LIBROS', 6);
INSERT INTO HIJO VALUES(5, 'SOFÍA', 'LOPEZ', 11, 'BAILAR', 5);
INSERT INTO HIJO VALUES (6, 'ARMANDO', 'SANCHEZ', 15, 'GIMNASIO',9);
INSERT INTO HIJO VALUES (7, 'ANGELICA', 'PEREZ', 10, 'COCINAR',3);
INSERT INTO HIJO VALUES (8, 'MICHELLE', 'LOPEZ', 18, 'VER SERIES',11);
INSERT INTO HIJO VALUES(9, 'JUAN', 'MATUS', 10, 'DIBUJAR', 8);
INSERT INTO HIJO VALUES(10, 'ITZEL', 'LOPEZ', 16, 'VIDEOJUEGOS',11);
INSERT INTO HIJO VALUES(11, 'KARLA', 'AQUINO', 14, 'CANTAR', 9);

SELECT * FROM HIJO;

SELECT * FROM HIJO H
INNER JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

SELECT * FROM HIJO H
LEFT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;
    
    --USO DE LEFT JOIN QUITANDO COINCIDENCIAS 
SELECT * FROM HIJO H
LEFT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE
WHERE H.PADRE_ID IS NULL;

--USO DELRIGHT JOIN

SELECT * FROM HIJO H
RIGHT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

--USO DE RIHT JOIN SIN COINCIDENCIAS 
SELECT * FROM HIJO H
RIGHT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE
WHERE H.PADRE_ID IS NULL;

SELECT * FROM HIJO H
FULL JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

--SIN COINCIDENCIAS
SELECT * FROM HIJO H
FULL JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE
WHERE H.PADRE_ID IS NULL
OR P.ID_PADRE IS NULL;

    