CREATE TABLE LIBRO(
    ID_LIBRO NUMBER,
    NOMBRE NVARCHAR2(100),
    AUTOR NVARCHAR2(100),
    GENERO NUMBER,
    NO_PAGINAS NUMBER,
    PRECIO NUMBER,
    EDITORIAL NVARCHAR2(100),
    CONSTRAINT LIBRO_PK PRIMARY KEY(ID_LIBRO)
    );
    
INSERT INTO LIBRO VALUES(1, 'LOS JUEGOS DEL HAMBRE', 'SUZZANE COLLINS', 3, 600, 500, 'COMETA');
INSERT INTO LIBRO VALUES(2, 'FLORES EN EL ATICO', 'V. ANDREWS', 4, 800, 640, 'DE BOLSILLO');
INSERT INTO LIBRO VALUES(3, 'CARRETERA MALDITA', NULL, NULL, NULL, 840, 'DE BOLSILLO');
INSERT INTO LIBRO VALUES(4, 'CIEN AÑOS DE SOLEDAD', 'GABRIEL GARCÍA MÁRQUEZ', 6, 1200, 500, 'SUDAMERICANA');
INSERT INTO LIBRO VALUES(5, 'EL PRINCIPITO', 'ANTOINE DE SAINT-EXUPÉRY', 6, 950, 150, 'SALAMANDRA');
INSERT INTO LIBRO VALUES (6, 'HARRY POTTER Y LA PIEDRA FILOSOFAL', 'J.K. ROWLING', 1, 309, 450, 'SALAMANDRA');
INSERT INTO LIBRO VALUES (7, 'EL SEÑOR DE LOS ANILLOS: LA COMUNIDAD DEL ANILLO', 'J.R.R. TOLKIEN', 1, 531, 580, 'MINOTAURO');
INSERT INTO LIBRO VALUES(8, 'MIL BESOS TUYOS', 'TILLIE COLE', 1 , 500, 500, 'ROCA');
INSERT INTO LIBRO VALUES(9, 'THE MAZE RUNNER', 'JAMES DASHER', 3 , 700, 900, 'DELACORTE PRESS');

SELECT * FROM LIBRO;

ALTER 
SELECT ID_LIBRO, NOMBRE, AUTOR,
(
    CASE GENERO
    WHEN 1 THEN 'DRAMA'
    WHEN 2 THEN 'TERROR'
    WHEN 3 THEN 'CIENCIA FICCION'
    WHEN 4 THEN 'NOVELA'
    WHEN 5 THEN 'THRILLER'
    WHEN 6 THEN 'COMEDIA'
    ELSE ' SIN GENERO'
    END
) AND GENERO, NO_PAGINAS, PRECIO, EDITORIAL FROM LIBRO;

SELECT ID_LIBRO, NOMBRE, GENERO, NO_PAGINAS,
(
    CASE
    WHEN PRECIO > 400 THEN 'ES CARO: ' || TO_CHAR(PRECIO, '$9,999,00') || 'PESOS'
    WHEN PRECIO < 400 THEN 'ES BARATO: ' || TO_CHAR(PRECIO, '$9,999,00') || 'PESOS'
    ELSE 'PRECIO NO DEFINIDO'
    END
)AS PRECIO, EDITORIAL FROM LIBRO;