--SORE PROCEDURE
SELECT * FROM COMPUTADORA;
DELETE  FROM COMPUTADORA;

CREATE TABLE  COMPUTADORA_PRD(
    ID_COMPU NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    RAM NUMBER,
    PROCESADOR NVARCHAR2(100),
    PRECIO NUMBER,
    CONSTRAINT COMPU_PRD_PK PRIMARY KEY(ID_COMPU)
);

INSERT INTO COMPUTADORA VALUES(1,'ASUS', 'ROG STRIX', 16, 'INTEL CORE i7 12th', 15000);
  INSERT INTO COMPUTADORA VALUES (2, 'LENOVO', 'IDEA PAD', 8, 'AMD RYZEN 7', 13500);
  INSERT INTO COMPUTADORA VALUES (3, 'HP', 'OMEN 15', 32, 'AMD Ryzen 9 5900HX', 7500);
INSERT INTO COMPUTADORA VALUES (4, 'DELL', 'XPS 15', 64, 'INTEL Core i9 13th', 12000);
INSERT INTO COMPUTADORA  VALUES (5, 'Lenovo', 'Legion 5', 16, 'Intel Core i7 11th', 16000);
COMMIT;

SELECT * FROM COMPUTADORA;
SELECT * FROM COMPUTADORA_PRD;

CREATE OR REPLACE PROCEDURE PR_RESPALDO_COMPUTADORA
IS
--DECLARACION DE VARIABLES
BEGIN
    DELETE  FROM COMPUTADORA_PRD; --LIMPIAR MI TABLA PARA RECIBIR EL NUEVO RESPALDO
    
    INSERT INTO COMPUTADORA_PRD (ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO)
    SELECT ID_COMPU, MARCA, MODELO, RAM, PROCESADOR, PRECIO FROM COMPUTADORA;
END PR_RESPALDO_COMPUTADORA;
/
SELECT * FROM COMPUTADORA;
SELECT * FROM COMPUTADORA_PRD;

EXECUTE PR_RESPALDO_COMPUTADORA;