CREATE TABLE  CELULAR_PRD(
     ID_CEL NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    PRECIO NUMBER,
    CONSTRAINT CEL_PRD_PK PRIMARY KEY(ID_CEL)
);
DELETE  FROM CELULAR;

CREATE OR REPLACE PROCEDURE PR_RESPALDO_CELULAR
IS
--DECLARACION DE VARIABLES
BEGIN
    DELETE  FROM CELULAR_PRD; --LIMPIAR MI TABLA PARA RECIBIR EL NUEVO RESPALDO
    
    INSERT INTO CELULAR_PRD (ID_CEL, MARCA, MODELO, PRECIO)
    SELECT ID_CEL, MARCA, MODELO, PRECIO FROM CELULAR;
END PR_RESPALDO_CELULAR;
/

INSERT INTO CELULAR VALUES (1, 'SAMSUNG', 'A53', 5500);
INSERT INTO CELULAR VALUES (2, 'APPLE', 'IPHONE 13', 18000);
INSERT INTO CELULAR VALUES (3, 'XIAOMI', 'REDMI NOTE 12', 4600);
INSERT INTO CELULAR VALUES (4, 'Motorola', 'Edge 30', 9800);
INSERT INTO CELULAR VALUES (5, 'Huawei', 'P50 Pro', 18000);
COMMIT;
SELECT * FROM CELULAR;
SELECT * FROM CELULAR_PRD;

EXECUTE PR_RESPALDO_CELULAR;