CREATE SEQUENCE S_ID_BIT_COMPU
START WITH 1
MAXVALUE 9999
MINVALUE 1
NOCYCLE;
/

SELECT S_ID_BIT_COMPU.NEXTVAL FROM DUAL;

--EJERCICIO 
--TABLA
CREATE TABLE CELULAR (
    ID_CEL NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    PRECIO NUMBER,
    CONSTRAINT PK_CELULAR PRIMARY KEY(ID_CEL)
);
--BITACORA
CREATE TABLE BIT_CELULAR (
    ID_BIT NUMBER,
    
    ID_CEL NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    PRECIO NUMBER,
    --VALORES VIEJOS
    MARCA_OLD NVARCHAR2(100),
    MODELO_OLD NVARCHAR2(100),
    PRECIO_OLD NUMBER,
    --CAMPOS DE CONTROL
    USUARIO NVARCHAR2(100),
    FECHA_MOV DATE,
    MOVIMIENTO NVARCHAR2(100),
    CONSTRAINT PK_BIT_CELULAR PRIMARY KEY(ID_BIT)
);

--SECUENCIA ID
CREATE SEQUENCE S_ID_BIT_CELULAR START WITH 1 INCREMENT BY 1;

--CREACION DEL TIGGER
CREATE OR REPLACE TRIGGER TR_CELULAR_BIT
AFTER INSERT OR UPDATE OR DELETE ON CELULAR
FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
BEGIN
    SELECT S_ID_BIT_CELULAR.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;

    IF INSERTING THEN
        INSERT INTO BIT_CELULAR(ID_BIT, ID_CEL, MARCA, MODELO, PRECIO,
        MARCA_OLD, MODELO_OLD, PRECIO_OLD,USUARIO, FECHA_MOV, MOVIMIENTO)
        VALUES (LV_ID_BIT, :NEW.ID_CEL, :NEW.MARCA, :NEW.MODELO, :NEW.PRECIO,
        NULL, NULL, NULL, LV_USUARIO, LV_FECHA, 'INSERT');

    ELSIF UPDATING THEN
        INSERT INTO BIT_CELULAR(ID_BIT, ID_CEL, MARCA, MODELO, PRECIO,
        MARCA_OLD, MODELO_OLD, PRECIO_OLD, USUARIO, FECHA_MOV, MOVIMIENTO)
        VALUES (LV_ID_BIT, :NEW.ID_CEL, :NEW.MARCA, :NEW.MODELO, :NEW.PRECIO,
        :OLD.MARCA, :OLD.MODELO, :OLD.PRECIO, LV_USUARIO, LV_FECHA, 'UPDATE');

    ELSIF DELETING THEN
        INSERT INTO BIT_CELULAR(ID_BIT, ID_CEL, MARCA, MODELO, PRECIO,
        MARCA_OLD, MODELO_OLD, PRECIO_OLD, USUARIO, FECHA_MOV, MOVIMIENTO)
        VALUES (LV_ID_BIT, :OLD.ID_CEL, NULL, NULL, NULL,
        :OLD.MARCA, :OLD.MODELO, :OLD.PRECIO,
        LV_USUARIO, LV_FECHA, 'DELETE');
    END IF;
END TR_CELULAR_BIT;
/
SELECT * FROM CELULAR;
SELECT * FROM BIT_CELULAR;


-- INSERTAR REGISTROS
INSERT INTO CELULAR VALUES (1, 'SAMSUNG', 'A53', 5500);
INSERT INTO CELULAR VALUES (2, 'APPLE', 'IPHONE 13', 18000);
INSERT INTO CELULAR VALUES (3, 'XIAOMI', 'REDMI NOTE 12', 4600);
INSERT INTO CELULAR VALUES (4, 'Motorola', 'Edge 30', 9800);
INSERT INTO CELULAR VALUES (5, 'Huawei', 'P50 Pro', 18000);

-- ACTUALIZAR UN REGISTRO
UPDATE CELULAR SET MODELO = 'iPhone 14 Pro Max' WHERE ID_CEL = 2;
UPDATE CELULAR SET PRECIO = 5000 WHERE ID_CEL = 3;

-- ELIMINAR REGISTRO
DELETE FROM CELULAR;
DELETE FROM BIT_CELULAR;

/

CREATE OR REPLACE TRIGGER TR_I_U_D_CELULAR
AFTER INSERT OR UPDATE OR DELETE ON CELULAR
FOR EACH ROW
DECLARE
    LV_ID_BIT NUMBER;
    LV_USUARIO NVARCHAR2(100);
    LV_FECHA DATE;
    LV_MOV NVARCHAR2(100);
BEGIN
    
    SELECT S_ID_BIT_CELULAR.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;

    IF INSERTING THEN
        LV_MOV := 'INSERT';
    ELSIF UPDATING THEN
        LV_MOV := 'UPDATE';
    ELSIF DELETING THEN
        LV_MOV := 'DELETE';
    END IF;
        INSERT INTO BIT_CELULAR(ID_BIT, USUARIO, FECHA_MOV, MOVIMIENTO)
        VALUES (LV_ID_BIT,  LV_USUARIO, LV_FECHA, LV_MOV);
   
END TR_I_U_D_CELULAR;
/

INSERT INTO CELULAR VALUES (1, 'SAMSUNG', 'A53', 5500);
INSERT INTO CELULAR VALUES (2, 'APPLE', 'IPHONE 13', 18000);
INSERT INTO CELULAR VALUES (3, 'XIAOMI', 'REDMI NOTE 12', 4600);
INSERT INTO CELULAR VALUES (4, 'Motorola', 'Edge 30', 9800);

DELETE FROM CELULAR;
SELECT ID_BIT, USUARIO, FECHA_MOV, MOVIMIENTO FROM BIT_CELULAR;

SELECT * FROM CELULAR;

--RESPALDO
CREATE TABLE  CELULAR_PRD(
     ID_CEL NUMBER,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    PRECIO NUMBER,
    CONSTRAINT CEL_PRD_PK PRIMARY KEY(ID_CEL)
);
DELETE  FROM CELULAR;

CREATE OR REPLACE PROCEDURE PR_RESPALDO_CELULAR
IS
--DECLARACION DE VARIABLES
BEGIN
    DELETE  FROM CELULAR_PRD; --LIMPIAR MI TABLA PARA RECIBIR EL NUEVO RESPALDO
    
    INSERT INTO CELULAR_PRD (ID_CEL, MARCA, MODELO, PRECIO)
    SELECT ID_CEL, MARCA, MODELO, PRECIO FROM CELULAR;
END PR_RESPALDO_CELULAR;
/

INSERT INTO CELULAR VALUES (1, 'SAMSUNG', 'A53', 5500);
INSERT INTO CELULAR VALUES (2, 'APPLE', 'IPHONE 13', 18000);
INSERT INTO CELULAR VALUES (3, 'XIAOMI', 'REDMI NOTE 12', 4600);
INSERT INTO CELULAR VALUES (4, 'Motorola', 'Edge 30', 9800);
INSERT INTO CELULAR VALUES (5, 'Huawei', 'P50 Pro', 18000);
COMMIT;
SELECT * FROM CELULAR;
SELECT * FROM CELULAR_PRD;

EXECUTE PR_RESPALDO_CELULAR;



