--VISTAS O VIEWS

SELECT * FROM PADRE;
SELECT * FROM HIJO;

CREATE OR REPLACE VIEW V_PADRE_HIJO_DETALLE
AS
SELECT H.ID_HIJO, H.NOMBRE, H.APELLIDO, H.EDAD, NVL(H.HOBBIE, 'SIN HOBBIE') AS HOBBIE,
NVL(H.PADRE_ID, 0) AS PADRE FROM HIJO H LEFT JOIN PADRE P ON H.PADRE_ID = P.ID_PADRE;

SELECT * FROM V_PADRE_HIJO_DETALLE;