
--FUNCIONES PL/SQL

CREATE OR REPLACE FUNCTION FN_NUMERO_PAR(P_NUMERO IN NUMBER)
RETURN NVARCHAR2
IS
    LV_RESULTADO NVARCHAR2(100);
BEGIN
    IF MOD(P_NUMERO, 2) = 0 THEN
    LV_RESULTADO := 'EL NUMERO: ' || P_NUMERO || ' ES PAR';
    ELSE 
    LV_RESULTADO := 'EL NUMERO: ' || P_NUMERO || ' NO ES PAR';
    END IF;
    RETURN LV_RESULTADO;
END FN_NUMERO_PAR;
/

BEGIN
DBMS_OUTPUT.PUT_LINE(FN_NUMERO_PAR(10));
END;
/

SELECT FN_NUMERO_PAR(21) FROM DUAL;
/


--•1.- REALIZAR UNA FUNCION QUE CALCULE EL AREA DEL CIRCULO Y QUE RECIBA COMO PARAMETRO EL RADIO
CREATE OR REPLACE FUNCTION AREA_CIRCULO(RADIO NUMBER)
RETURN NUMBER
IS
    AREA NUMBER;
BEGIN
    AREA := 3.1416 * RADIO * RADIO;
    RETURN AREA;
END;
/

SELECT AREA_CIRCULO(5) FROM DUAL;

--2•- USAR UNA FUNCION QUE RECIBA UN NUMERO DEL 1 AL 12 Y DEVUELVA EL NOMBRE DEL MES CORRESPONDIENIE
CREATE OR REPLACE FUNCTION NOMBRE_MES(NUMERO NUMBER)
RETURN VARCHAR2
IS
    MES_NOMBRE VARCHAR2(20);
BEGIN
    MES_NOMBRE := TO_CHAR(TO_DATE(NUMERO, 'MM'), 'Month');
    RETURN (MES_NOMBRE);
END;
/
SELECT NOMBRE_MES(3) FROM DUAL;


--:3.- REALIZAR UNA FUNCION QUE RECIBA UN NUMERO Y DEVUELVA SU DOBLE
CREATE OR REPLACE FUNCTION DOBLE(NUMERO NUMBER)
RETURN NUMBER
IS
BEGIN
    RETURN NUMERO * 2;
END;
/
SELECT DOBLE(4) FROM DUAL;


--:4.- REALIZAR UNA FUNCION QUE CALCULE EL AREA DEL TRIANGULO, QUE RECIBA COMO PARAMETROS LA BASE Y ALTURA
CREATE OR REPLACE FUNCTION AREA_TRIANGULO(BASE NUMBER, ALTURA NUMBER)
RETURN NUMBER
IS
BEGIN
    RETURN (BASE * ALTURA) / 2;
END;
/
SELECT AREA_TRIANGULO(10, 5) FROM DUAL;

--5.- REALIZAR UNA FUNCION QUE RECIBA UN NUMERO DEL 1 AL 7 Y DEVULVA EL NOMBRE DEL DIA DE LA SEMANA
CREATE OR REPLACE FUNCTION DIA_SEMANA(numero NUMBER)
RETURN VARCHAR2
IS
    NOMBRE_DIA VARCHAR2(20);
BEGIN
    CASE NUMERO
        WHEN 1 THEN NOMBRE_DIA := 'LUNES';
        WHEN 2 THEN NOMBRE_DIA := 'MARTES';
        WHEN 3 THEN NOMBRE_DIA := 'MIERCOLES';
        WHEN 4 THEN NOMBRE_DIA := 'JUEVES';
        WHEN 5 THEN NOMBRE_DIA := 'VIERNES';
        WHEN 6 THEN NOMBRE_DIA := 'SABADO';
        WHEN 7 THEN NOMBRE_DIA := 'DOMINGO';
        ELSE
            NOMBRE_DIA := 'DIA INVALIDO';
    END CASE;

    RETURN NOMBRE_DIA;
END;
/

SELECT DIA_SEMANA(5) FROM DUAL;


--6.- REALIZAR UNA FUNCION QUE RECIBA UNA EDAD Y DEVUELVA UN MENSAJE INDICANDO SI ES MAYOR O MENOR DE EDAD
CREATE OR REPLACE FUNCTION VERIFICAR_EDAD(EDAD NUMBER)
RETURN VARCHAR2
IS
BEGIN
    IF EDAD >= 18 THEN
        RETURN 'ES MAYOR DE EDAD';
    ELSE
        RETURN 'ES MENOR DE EDAD';
    END IF;
END;
/

SELECT VERIFICAR_EDAD(17) FROM DUAL;

--:7.- REALIZAR UNA FUNCION QUE RECIBA UN NUMERO Y DEVUELVA SU CUADRADO
CREATE OR REPLACE FUNCTION CUADRADO(NUMERO NUMBER)
RETURN NUMBER
IS
BEGIN
    RETURN NUMERO * NUMERO;
END;
/
SELECT CUADRADO(6) FROM DUAL;


--:8.- REALIZAR UNA FUNCION QUE RECIBA UN NUMERO Y DEVUELVA UN MNESAJE INDICANDO SI ES MULTIPLO DE 3 O NO
CREATE OR REPLACE FUNCTION MULTIPLO_TRES(NUMERO NUMBER)
RETURN VARCHAR2
IS
BEGIN
    IF MOD(NUMERO, 3) = 0 THEN
        RETURN 'ES MULTIPLO DE 3';
    ELSE
        RETURN 'NO ES MULTIPLO DE 3';
    END IF;
END;
/
SELECT MULTIPLO_TRES(10) FROM DUAL;


--9.- REALIZAR UNA FUNCION QUE RECIBA 2 CADENAS (NOMBRE Y APELIDO) Y DEVUELVA EL NOMBRE COMPLETO
CREATE OR REPLACE FUNCTION NOMBRE_COMPLETO(NOMBRE VARCHAR2, APELLIDO VARCHAR2)
RETURN NVARCHAR2
IS
BEGIN
    RETURN NOMBRE || ' ' || APELLIDO;
END;
/
SELECT NOMBRE_COMPLETO('OMAR', 'CAMPOS') FROM DUAL;



