--CURSORES
CREATE TABLE LIBROS (
    ID_LIBRO NUMBER PRIMARY KEY,
    TITULO VARCHAR2(100),
    GENERO NUMBER, -- Se usará con valores como 1, 2, 3, etc.
    PRECIO NUMBER(10, 2)
);

SELECT * FROM LIBROS;
/
CREATE OR REPLACE PROCEDURE PR_DETALLE_LIBRO
IS
    --CURSOR
    CURSOR LIBRO_INFO IS
    SELECT NOMBRE, 
        (CASE GENERO
            WHEN 1 THEN 'DRAMA'
            WHEN 2 THEN 'TERROR'
            WHEN 3 THEN 'CIENCIA FICCION'
            WHEN 4 THEN 'NOVELA'
            WHEN 5 THEN 'THRILLER'
            WHEN 6 THEN 'COMEDIA'
            ELSE 'SIN GENERO'
        END) AS GENERO, PRECIO FROM LIBRO;
        
        LV_NOMBRE LIBRO.NOMBRE%TYPE;
        LV_GENERO NVARCHAR2(20);
        LV_PRECIO NUMBER;
BEGIN 
    --ABRIR CURSOR
    OPEN LIBRO_INFO;
    --RECUPERAR EL CURSOR Y MOSTRAR LOS DATOS CON UN LOOP
        LOOP
            FETCH LIBRO_INFO INTO LV_NOMBRE, LV_GENERO, LV_PRECIO;
            
            EXIT WHEN LIBRO_INFO%NOTFOUND;
            
            --MOSTRAR LOS DATOS DEL CURSOR
            DBMS_OUTPUT.PUT_LINE('NOMBRE DEL LIBRO: ' || LV_NOMBRE || ' ,DE GENERO ' || LV_GENERO || 
            ' , TIENE UN VALOR DE: ' || LV_PRECIO);
            
        END LOOP;
        
    CLOSE LIBRO_INFO;
END PR_DETALLE_LIBRO;
/

BEGIN
 PR_DETALLE_LIBRO;
 END;
 /

