--MODIFICAR LA SESION ACTUAL PARA LA EJECUCION DE SCRIPTS

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

--CREACION DEL USUARIO Y CONTRASEÑA

CREATE USER MARCO11 IDENTIFIED BY CURSO2024;

GRANT ALL PRIVILEGES TO MARCO11;

