--crear con DDL

CREATE TABLE EMPLEADO(
    ID_CLIENTE NUMBER,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100)
    
);

--DML

INSERT INTO EMPLEADO VALUES(1,'RAUL', 'MORALES', 21, 'ADMINISTRADOR', 'RH');
COMMIT;--DEBEMOS CONFIRMAR LOS CAMBIOS AL TERMINAL CON LA TRANSACCION REALIZADA 

SELECT * FROM EMPLEADO;

--EJECUTAR ELIMINAR TABLA DDL

DROP TABLE EMPLEADO;--ELIMINA TODA LA TABLA

DELETE FROM EMPLEADO;--ELIMINA LOS REGISTROS DENTRO DE LA TABLA

--USO DE LOS CONSTRAINT
--CREAR ENTIDAD PRIMARY KEY

CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER, 
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100)
    
);

--SEGUNDA FORMA 

CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER, 
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100),
    PRIMARY KEY(ID_EMPLEADO)
    

);

--TERCERA FORMA 
CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER,
    NOMBRE NVARCHAR2(100),
    APP NVARCHAR2(100),
    EDAD NUMBER, 
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100),
    CONSTRAINT EMPLEADO_PK PRIMARY KEY(ID_EMPLEADO)
);





