--MODIFICAR LA SESION ACTUAL PARA LA EJECUCION DE SCRIPTS

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

--CREACION DEL USUARIO Y CONTRASEÑA

CREATE USER ANT IDENTIFIED BY MARCO123;

GRANT ALL PRIVILEGES TO ANT;
