--PAQUETES
CREATE TABLE LIBRO1 (
  ID_LIBRO NUMBER PRIMARY KEY,
  NOMBRE VARCHAR2(100),
  GENERO NUMBER,
  PRECIO NUMBER
);
INSERT INTO LIBRO1 (ID_LIBRO, NOMBRE, GENERO, PRECIO)
VALUES (1, 'CIEN AÑOS DE SOLEDAD', 4, 250);

INSERT INTO LIBRO1 (ID_LIBRO, NOMBRE, GENERO, PRECIO)
VALUES (2, 'LA CASA DE LOS ESPÍRITUS', 1, 180);

CREATE OR REPLACE PACKAGE PKG_GENERAL AS
    PROCEDURE PR_DETALLE_LIBRO;
END;

/
CREATE OR REPLACE PACKAGE BODY PKG_GENERAL AS 
  PROCEDURE PR_DETALLE_LIBRO
  IS
    --CURSOR
    CURSOR LIBRO_INFO IS
      SELECT NOMBRE, 
        CASE GENERO
          WHEN 1 THEN 'DRAMA'
          WHEN 2 THEN 'TERROR'
          WHEN 3 THEN 'CIENCIA FICCION'
          WHEN 4 THEN 'NOVELA'
          WHEN 5 THEN 'THRILLER'
          WHEN 6 THEN 'COMEDIA'
          ELSE 'SIN GENERO'
        END AS GENERO,
        PRECIO
      FROM LIBRO1;

    LV_NOMBRE LIBRO1.NOMBRE%TYPE;
    LV_GENERO NVARCHAR2(20);
    LV_PRECIO NUMBER;
  BEGIN 
    OPEN LIBRO_INFO;

    LOOP
      FETCH LIBRO_INFO INTO LV_NOMBRE, LV_GENERO, LV_PRECIO;
      EXIT WHEN LIBRO_INFO%NOTFOUND;

      DBMS_OUTPUT.PUT_LINE('NOMBRE DEL LIBRO: ' || LV_NOMBRE || 
                           ', DE GENERO: ' || LV_GENERO || 
                           ', TIENE UN VALOR DE: ' || LV_PRECIO);
       DBMS_OUTPUT.PUT_LINE(FN_NUMERO_PAR(ROUND(LV_PRECIO)));
                    
    END LOOP;

    CLOSE LIBRO_INFO;
  END PR_DETALLE_LIBRO;
END PKG_GENERAL;
/

EXECUTE PKG_GENERAL.PR_DETALLE_LIBRO;
