--;1.- REALIZAR UN CURSOR QUE MUESTRE EL TITULO Y PRECIO DE TODOS LOS LIBROS

DECLARE CURSOR TITULO_PRECIOS IS
    SELECT TITULO, PRECIO FROM LIBRO;
    
    LV_TITULO LIBRO.TITULO%TYPE;
    LV_PRECIO LIBRO.PRECIO%TYPE;
BEGIN
    OPEN TITULO_PRECIOS;
    LOOP
        FETCH TITULO_PRECIOS INTO LV_TITULO, LV_PRECIO;
        EXIT WHEN TITULO_PRECIOS%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('TITULO: ' || LV_TITULO || ' , PRECIO: ' || LV_PRECIO);
    END LOOP;
    CLOSE TITULO_PRECIOS;
END;
/


--2.- REALIZAR UN CURSOR QUE MUESTRE SOLO LOS LIBROS CON PRECIO MAYOR A 300 ORDENADOS POR PRECIOS DESCENDENIE
DECLARE CURSOR LIBROS_CAROS 
IS
        SELECT TITULO, PRECIO 
        FROM LIBRO 
        WHERE PRECIO > 300
        ORDER BY PRECIO DESC;
    
    LV_TITULO LIBRO.TITULO%TYPE;
    LV_PRECIO LIBRO.PRECIO%TYPE;
BEGIN
    OPEN LIBROS_CAROS;
    LOOP
        FETCH LIBROS_CAROS INTO LV_TITULO, LV_PRECIO;
        EXIT WHEN LIBROS_CAROS%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('LIBRO: ' || LV_TITULO || ' , PRECIO: ' || LV_PRECIO);
    END LOOP;
    CLOSE LIBROS_CAROS;
END;
/

SELECT * FROM LIBRO;

--3.- REALIZAR UN CURSOR PARA MOSIRAR LAS VENTAS (FECHA Y CANTIDAD) DE UN LIBRO DADO SU ID
DECLARE ID_LIBRO NUMBER := 1; -- Cambia este valor por el ID deseado

    CURSOR VENTAS_LIBRO IS
        SELECT FECHA_VENTA, CANTIDAD
        FROM VENTA
        WHERE LIBRO_ID = ID_LIBRO;
    
    LV_FECHA DATE;
    LV_CANTIDAD NUMBER;
BEGIN
    OPEN VENTAS_LIBRO;
    LOOP
        FETCH VENTAS_LIBRO INTO LV_FECHA, LV_CANTIDAD;
        EXIT WHEN VENTAS_LIBRO%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('FECHA: ' || LV_FECHA || ' , CANTIDAD: ' || LV_CANTIDAD);
    END LOOP;
    CLOSE VENTAS_LIBRO;
END;
/

--4.- REALIZAR UN CURSOR PARA MOSIRAR CADA LIBRO CON LA CANTIDAD TOTAL VENDIDA
CREATE OR REPLACE PROCEDURE TOTAL_EN_PESOS
IS
    CURSOR C_TOTAL_PESOS IS
        SELECT L.ID_LIBRO, L.TITULO, L.PRECIO, 
               NVL(SUM(V.CANTIDAD), 0) AS TOTAL_CANTIDAD
        FROM LIBRO L
        LEFT JOIN VENTA V ON L.ID_LIBRO = V.LIBRO_ID
        GROUP BY L.ID_LIBRO, L.TITULO, L.PRECIO;

    V_ID_LIBRO NUMBER;
    V_TITULO VARCHAR2(150);
    V_PRECIO NUMBER;
    V_TOTAL_CANTIDAD NUMBER;
    V_TOTAL_PESOS NUMBER;
BEGIN
    OPEN C_TOTAL_PESOS;
    LOOP
        FETCH C_TOTAL_PESOS INTO V_ID_LIBRO, V_TITULO, V_PRECIO, V_TOTAL_CANTIDAD;
        EXIT WHEN C_TOTAL_PESOS%NOTFOUND;
        V_TOTAL_PESOS := V_PRECIO * V_TOTAL_CANTIDAD;
        DBMS_OUTPUT.PUT_LINE('LIBRO: ' || V_TITULO || ' , TOTAL VENDIDO : ' || V_TOTAL_PESOS);
    END LOOP;
    CLOSE C_TOTAL_PESOS;
END;
/

BEGIN
    TOTAL_EN_PESOS;
END;






