--5.- REALIZAR UNA FUNCION QUE RECIBA UN NUMERO DEL 1 AL 7 Y DEVULVA EL NOMBRE DEL DIA DE LA SEMANA
CREATE OR REPLACE FUNCTION dia_semana(numero NUMBER)
RETURN VARCHAR2
IS
    nombre_dia VARCHAR2(100);
BEGIN
    nombre_dia := TO_CHAR(TO_DATE(numero, 'D'), 'Day');
    RETURN RTRIM(nombre_dia);
END;
/
SELECT dia_semana(6) FROM DUAL;