--Parte 1: Creación de Esquema de Tablas

--TABLA EMPLEADO
CREATE TABLE EMPLEADO (
    ID_EMPLEADO NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    DEPARTAMENTO_ID NUMBER,
    SALARIO NUMBER,
    FECHA_INGRESO DATE,
    CONSTRAINT FK_DEP_EMPLEADO FOREIGN KEY (DEPARTAMENTO_ID)
        REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)
);
INSERT INTO EMPLEADO VALUES (1, 'Ana Pérez', 1, 4500, TO_DATE('2021-01-10','YYYY-MM-DD'));
INSERT INTO EMPLEADO VALUES (2, 'Carlos López', 2, 5200, TO_DATE('2020-03-15','YYYY-MM-DD'));
INSERT INTO EMPLEADO VALUES (3, 'María Gómez', 3, 4800, TO_DATE('2019-07-22','YYYY-MM-DD'));
INSERT INTO EMPLEADO VALUES (4, 'Jorge Ramírez', 4, 3000, TO_DATE('2022-09-01','YYYY-MM-DD'));
INSERT INTO EMPLEADO VALUES (5, 'Luisa Fernández', 5, 6500, TO_DATE('2018-12-05','YYYY-MM-DD'));




--TABLA DEPARTAMENTO
CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100)
);
INSERT INTO DEPARTAMENTO VALUES (1, 'VENTAS');
INSERT INTO DEPARTAMENTO VALUES (2, 'MARKETING');
INSERT INTO DEPARTAMENTO VALUES (3, 'DESARROLLO');
INSERT INTO DEPARTAMENTO VALUES (4, 'RH');
INSERT INTO DEPARTAMENTO VALUES (5, 'FINANZAS');



--TABLA PROYECTO
CREATE TABLE PROYECTO (
    ID_PROYECTO NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100),
    FECHA_INICIO DATE,
    FECHA_FIN DATE
);
INSERT INTO PROYECTO VALUES (1, 'PROYECTO INNOVACIÓN', TO_DATE('2025-03-01', 'YYYY-MM-DD'), TO_DATE('2025-09-30', 'YYYY-MM-DD'));
INSERT INTO PROYECTO VALUES (2, 'PROYECTO NEXUS', TO_DATE('2025-05-15', 'YYYY-MM-DD'), TO_DATE('2025-11-15', 'YYYY-MM-DD'));
INSERT INTO PROYECTO VALUES (3, 'PROYECTO TITAN', TO_DATE('2025-01-10', 'YYYY-MM-DD'), TO_DATE('2025-06-10', 'YYYY-MM-DD'));
INSERT INTO PROYECTO VALUES (4, 'PROYECTO PRISMA', TO_DATE('2024-12-01', 'YYYY-MM-DD'), TO_DATE('2025-04-01', 'YYYY-MM-DD'));
INSERT INTO PROYECTO VALUES (5, 'PROYECTO ATLAS', TO_DATE('2025-02-20', 'YYYY-MM-DD'), TO_DATE('2025-12-20', 'YYYY-MM-DD'));



SELECT * FROM ASIGNACION;

--TABLA ASIGNACION 
CREATE TABLE ASIGNACION (
    ID_ASIGNACION NUMBER PRIMARY KEY,
    EMPLEADO_ID NUMBER,
    PROYECTO_ID NUMBER,
    HORAS_TRABAJADAS NUMBER,
    CONSTRAINT FK_EMP_ASIG FOREIGN KEY (EMPLEADO_ID)
        REFERENCES EMPLEADO(ID_EMPLEADO),
    CONSTRAINT FK_PROY_ASIG FOREIGN KEY (PROYECTO_ID)
        REFERENCES PROYECTO(ID_PROYECTO)
);
INSERT INTO ASIGNACION VALUES (1, 1, 1, 120);
INSERT INTO ASIGNACION VALUES (2, 2, 1, 90);
INSERT INTO ASIGNACION VALUES (3, 3, 2, 100);
INSERT INTO ASIGNACION VALUES (4, 4, 3, 50);
INSERT INTO ASIGNACION VALUES (5, 5, 4, 200);




--2. Consultas con Funciones de Agregación
--El salario promedio de los empleados en cada departamento.
SELECT D.NOMBRE AS DEPARTAMENTO,
    ROUND(AVG(E.SALARIO), 2) AS SALARIO_PROMEDIO
FROM EMPLEADO E
INNER JOIN DEPARTAMENTO D ON E.DEPARTAMENTO_ID = D.ID_DEPARTAMENTO
GROUP BY  D.NOMBRE;


--El número total de proyectos asignados a cada empleado.
SELECT E.NOMBRE AS EMPLEADO,
    COUNT(A.ID_ASIGNACION) AS TOTAL_PROYECTOS
FROM EMPLEADO E
RIGHT JOIN ASIGNACION A ON E.ID_EMPLEADO = A.EMPLEADO_ID
GROUP BY E.NOMBRE;


--La duración total de cada proyecto (diferencia entre la fecha de inicio y la fecha de fin).
SELECT NOMBRE AS PROYECTO,
    FECHA_INICIO,
    FECHA_FIN,
    FECHA_FIN - FECHA_INICIO AS DURACION_DIAS
FROM PROYECTO;


--3. Consultas con JOINs
--Los nombres de los empleados junto con el nombre del departamento al que pertenecen.
SELECT 
    E.NOMBRE AS EMPLEADO,
    D.NOMBRE AS DEPARTAMENTO
FROM EMPLEADO E
INNER JOIN DEPARTAMENTO D ON E.DEPARTAMENTO_ID = D.ID_DEPARTAMENTO;


--Los nombres de los proyectos junto con los nombres de los empleados asignados a esos proyectos y las horas trabajadas.
SELECT 
    P.NOMBRE AS PROYECTO,
    E.NOMBRE AS EMPLEADO,
    A.HORAS_TRABAJADAS
FROM ASIGNACION A
INNER JOIN EMPLEADO E ON A.EMPLEADO_ID = E.ID_EMPLEADO
INNER JOIN PROYECTO P ON A.PROYECTO_ID = P.ID_PROYECTO;

--4. Consultas con CASE
--Mostrar el salario de los empleados junto con una etiqueta que indique si el salario es "Alto" (> 5000), "Medio" (2000-5000) o "Bajo" (< 2000).
SELECT 
    NOMBRE AS EMPLEADO,
    SALARIO,
    CASE 
        WHEN SALARIO > 5000 THEN 'ALTO'
        WHEN SALARIO BETWEEN 2000 AND 5000 THEN 'MEDIO'
        WHEN SALARIO < 2000 THEN 'BAJO'
        ELSE 'SALARIO NO DEFINIDO'
    END AS CLASIFICACION_SALARIO
FROM EMPLEADO;
    
--Mostrar el nombre del proyecto y la duración del proyecto, junto con una etiqueta que indique si el proyecto está "Activo" 
--(si la fecha actual está dentro del rango) o "Inactivo".

SELECT 
    NOMBRE AS PROYECTO,
    FECHA_INICIO,
    FECHA_FIN,
    (FECHA_FIN - FECHA_INICIO) AS DURACION_EN_DIAS,
    CASE 
        WHEN SYSDATE BETWEEN FECHA_INICIO AND FECHA_FIN THEN 'ACTIVO'
        ELSE 'INACTIVO'
    END AS ESTADO_PROYECTO
FROM PROYECTO;

--Parte 3: Procedimientos PL/SQL

/*Tome como parámetro el ID_DEPARTAMENTO.
Tome como parámetro el ID_DEPARTAMENTO.
Imprima los nombres y salarios de todos los empleados en ese departamento.
Si el departamento no tiene empleados, imprima un mensaje indicando que no hay empleados en ese departamento.
*/
CREATE OR REPLACE PROCEDURE PR_EMPLEADOS_X_DEPARTAMENTO(P_ID_DEP IN NUMBER)
IS
    V_CONTADOR NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO V_CONTADOR
    FROM EMPLEADO
    WHERE DEPARTAMENTO_ID = P_ID_DEP;

    IF V_CONTADOR = 0 THEN
        DBMS_OUTPUT.PUT_LINE('NO HAY EMPLEADOS EN ESE DEPARTAMENTO.');
    ELSE
        FOR EMP IN (
            SELECT NOMBRE, SALARIO
            FROM EMPLEADO
            WHERE DEPARTAMENTO_ID = P_ID_DEP
        )
        LOOP
            DBMS_OUTPUT.PUT_LINE('EMPLEADO: ' || EMP.NOMBRE || ' , SALARIO: ' || EMP.SALARIO);
        END LOOP;
    END IF;
END;

/
BEGIN
    PR_EMPLEADOS_POR_DEPARTAMENTO(2);
END;
/

/*Parte 4: Ejercicio de Aplicación
Calcule el total de horas trabajadas por cada empleado en todos los proyectos.
Actualice la tabla EMPLEADO con un nuevo campo TOTAL_HORAS que almacene este total.
Imprima un mensaje para cada empleado indicando el total de horas trabajadas.

*/

ALTER TABLE EMPLEADO ADD TOTAL_HORAS NUMBER;
CREATE OR REPLACE PROCEDURE PR_ACTUALIZAR_TOTAL_HORAS
IS
BEGIN
    UPDATE EMPLEADO E
    SET TOTAL_HORAS = (
        SELECT NVL(SUM(A.HORAS_TRABAJADAS), 0)
        FROM ASIGNACION A
        WHERE A.EMPLEADO_ID = E.ID_EMPLEADO
    );

    FOR EMP IN (
        SELECT NOMBRE, TOTAL_HORAS FROM EMPLEADO
    )
    LOOP
        DBMS_OUTPUT.PUT_LINE('EMPLEADO: ' || EMP.NOMBRE || ' , TOTAL HORAS TRABAJADAS: ' || EMP.TOTAL_HORAS);
    END LOOP;
END;
/


BEGIN
    PR_CALCULAR_HORAS;
END;
/

/*7. Crear y Consultar una Vista
Instrucciones:
Crear la Vista: Escribe una vista que muestre la información de los empleados junto con el nombre de su departamento y el total de horas 
trabajadas en todos los proyectos. La vista debe incluir los siguientes campos:
ID_EMPLEADO
NOMBRE_EMPLEADO
DEPARTAMENTO
TOTAL_HORAS_TRABAJADAS

*/

CREATE OR REPLACE VIEW V_EMPLEADOS AS
SELECT 
    E.ID_EMPLEADO,
    E.NOMBRE AS NOMBRE_EMPLEADO,
    D.NOMBRE AS DEPARTAMENTO,
    NVL(SUM(A.HORAS_TRABAJADAS), 0) AS TOTAL_HORAS_TRABAJADAS
FROM 
    EMPLEADO E
    JOIN DEPARTAMENTO D ON E.DEPARTAMENTO_ID = D.ID_DEPARTAMENTO
    LEFT JOIN ASIGNACION A ON E.ID_EMPLEADO = A.EMPLEADO_ID
GROUP BY 
    E.ID_EMPLEADO, E.NOMBRE, D.NOMBRE;
/
    
SELECT *
FROM V_EMPLEADOS
WHERE TOTAL_HORAS_TRABAJADAS > 100
  AND UPPER(NOMBRE_EMPLEADO) LIKE '%A%';
  
/*Parte 5: Actividades Avanzadas (Funciones, Paquetes y Cursores)

Actividad 1: Función que devuelve el nombre del proyecto más largo
Crea una función que devuelva el nombre del proyecto con mayor duración en días (fecha_fin - fecha_inicio).

*/

CREATE OR REPLACE FUNCTION FN_PROYECTO_MAS_LARGO
RETURN VARCHAR2
IS
    V_NOMBRE_PROYECTO VARCHAR2(100);
BEGIN
    SELECT NOMBRE
    INTO V_NOMBRE_PROYECTO
    FROM PROYECTO
    WHERE (FECHA_FIN - FECHA_INICIO) = (
        SELECT MAX(FECHA_FIN - FECHA_INICIO)
        FROM PROYECTO
    );

    RETURN V_NOMBRE_PROYECTO;

END;
/
SELECT * FROM PROYECTO;

SELECT FN_PROYECTO_MAS_LARGO FROM DUAL;


/*Actividad 2: Función que clasifica un proyecto
Crea una función que reciba un ID_PROYECTO y devuelva un mensaje como:
'Corto' si dura menos de 30 días.
'Mediano' entre 30 y 90 días.
'Largo' si dura más de 90 días.

*/
CREATE OR REPLACE FUNCTION FN_CLASIFICAR_PROYECTO (P_ID_PROYECTO NUMBER)
RETURN VARCHAR2
IS
    V_DURACION NUMBER;
BEGIN
    SELECT FECHA_FIN - FECHA_INICIO
    INTO V_DURACION
    FROM PROYECTO
    WHERE ID_PROYECTO = P_ID_PROYECTO;

    IF V_DURACION < 30 THEN
        RETURN 'CORTO';
    ELSIF V_DURACION BETWEEN 30 AND 90 THEN
        RETURN 'MEDIANO';
    ELSE
        RETURN 'LARGO';
    END IF;
END;
/

SELECT FN_CLASIFICAR_PROYECTO(2) AS CLASIFICACION FROM DUAL;

/*Actividad 3: Procedimiento con cursor y condiciones
Crea un procedimiento que:
Recorra todos los empleados de un departamento dado (usando cursor).
Imprima sus nombres y, si tienen más de 100 horas trabajadas en total, que también imprima: "Empleado con alta carga de trabajo"

*/

CREATE OR REPLACE PROCEDURE PR_CARGA_TRABAJO_DEPTO (
    P_ID_DEPARTAMENTO IN NUMBER
)
IS
    CURSOR C_EMPLEADOS IS
        SELECT E.ID_EMPLEADO, E.NOMBRE,
               NVL(SUM(A.HORAS_TRABAJADAS), 0) AS TOTAL_HORAS
        FROM EMPLEADO E
        LEFT JOIN ASIGNACION A ON E.ID_EMPLEADO = A.EMPLEADO_ID
        WHERE E.DEPARTAMENTO_ID = P_ID_DEPARTAMENTO
        GROUP BY E.ID_EMPLEADO, E.NOMBRE;

    V_ID_EMPLEADO   EMPLEADO.ID_EMPLEADO%TYPE;
    V_NOMBRE        EMPLEADO.NOMBRE%TYPE;
    V_TOTAL_HORAS   NUMBER;
BEGIN
    OPEN C_EMPLEADOS;
    LOOP
        FETCH C_EMPLEADOS INTO V_ID_EMPLEADO, V_NOMBRE, V_TOTAL_HORAS;
        EXIT WHEN C_EMPLEADOS%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE('EMPLEADO: ' || V_NOMBRE || ' , TOTAL: ' || V_TOTAL_HORAS);

        IF V_TOTAL_HORAS > 100 THEN
            DBMS_OUTPUT.PUT_LINE(' EMPLEADO CON ALTA CARGA DE TRABAJO');
        END IF;
    END LOOP;
    CLOSE C_EMPLEADOS;
END;
/

BEGIN
    PR_CARGA_TRABAJO_DEPTO(1);
END;

/*Actividad 4: Paquete EMPLEADO_UTILS
Declara un paquete con:
Una función FN_CLASIFICAR_SALARIO que reciba un salario y retorne 'ALTO', 'MEDIO', 'BAJO'.
Un procedimiento PR_REPORTE_EMPLEADOS que imprima ID, nombre y salario clasificado de todos los empleados.
Un cursor declarado en el paquete para recorrer los empleados.
*/

CREATE OR REPLACE PACKAGE EMPLEADO_UTILS AS
    FUNCTION FN_CLASIFICAR_SALARIO(P_SALARIO NUMBER) RETURN VARCHAR2;

    PROCEDURE PR_REPORTE_EMPLEADOS;

    CURSOR C_EMPLEADOS IS
        SELECT ID_EMPLEADO, NOMBRE, SALARIO FROM EMPLEADO;
END EMPLEADO_UTILS;
/

CREATE OR REPLACE PACKAGE BODY EMPLEADO_UTILS AS

    FUNCTION FN_CLASIFICAR_SALARIO(P_SALARIO NUMBER) RETURN VARCHAR2 IS
    BEGIN
        IF P_SALARIO > 5000 THEN
            RETURN 'ALTO';
        ELSIF P_SALARIO BETWEEN 2000 AND 5000 THEN
            RETURN 'MEDIO';
        ELSE
            RETURN 'BAJO';
        END IF;
    END FN_CLASIFICAR_SALARIO;

    PROCEDURE PR_REPORTE_EMPLEADOS IS
        V_ID_EMPLEADO EMPLEADO.ID_EMPLEADO%TYPE;
        V_NOMBRE      EMPLEADO.NOMBRE%TYPE;
        V_SALARIO     EMPLEADO.SALARIO%TYPE;
        V_CLASIFICACION VARCHAR2(10);
    BEGIN
        OPEN C_EMPLEADOS;
        LOOP
            FETCH C_EMPLEADOS INTO V_ID_EMPLEADO, V_NOMBRE, V_SALARIO;
            EXIT WHEN C_EMPLEADOS%NOTFOUND;

            V_CLASIFICACION := FN_CLASIFICAR_SALARIO(V_SALARIO);

            DBMS_OUTPUT.PUT_LINE('ID: ' || V_ID_EMPLEADO || ', NOMBRE: ' || V_NOMBRE || 
                                 ', SALARIO: ' || V_SALARIO || ' -> ' || V_CLASIFICACION);
        END LOOP;
        CLOSE C_EMPLEADOS;
    END PR_REPORTE_EMPLEADOS;

END EMPLEADO_UTILS;
/
BEGIN
    EMPLEADO_UTILS.PR_REPORTE_EMPLEADOS;
END;
/

/*Actividad 5: Uso de cursores implícitos
Crea un procedimiento que:
Inserte una nueva asignación para un empleado.
Verifique con SQL%ROWCOUNT si se insertó correctamente.
Imprima un mensaje dependiendo del resultado.
*/

CREATE OR REPLACE PROCEDURE PR_INSERTAR_ASIGNACION (
    P_ID_ASIGNACION   IN NUMBER,
    P_EMPLEADO_ID     IN NUMBER,
    P_PROYECTO_ID     IN NUMBER,
    P_HORAS_TRABAJADAS IN NUMBER
)
IS
BEGIN

    INSERT INTO ASIGNACION (ID_ASIGNACION, EMPLEADO_ID, PROYECTO_ID, HORAS_TRABAJADAS)
    VALUES (P_ID_ASIGNACION, P_EMPLEADO_ID, P_PROYECTO_ID, P_HORAS_TRABAJADAS);

    
    IF SQL%ROWCOUNT = 1 THEN --DEVUELVE EL NUMERO DE FILAS
        DBMS_OUTPUT.PUT_LINE(' ASIGNACION INSERTADA CORRECTAMENTE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('NO SE INSERTO LA ASIGNACIONO');
    END IF;

END;
/
BEGIN
    PR_INSERTAR_ASIGNACION(7, 4, 4, 40);
END;
/

/*Actividad 6: Cursor FOR y manejo de excepciones
Crea un procedimiento que:
Use un cursor FOR para recorrer todos los proyectos.
Imprima su nombre y duración.
Si la duración es negativa (fecha_fin < fecha_inicio), lance una excepción y registre un mensaje: 'Error en proyecto: [NOMBRE]'.

*/
CREATE OR REPLACE PROCEDURE PR_REPORTE_PROYECTOS IS

  EXCEPTION_PROYECTO_ERR EXCEPTION;
  ERROR_MSG VARCHAR2(100);

BEGIN
  FOR REC IN (SELECT ID_PROYECTO, NOMBRE, FECHA_INICIO, FECHA_FIN FROM PROYECTO) LOOP
    DECLARE
      DURACION NUMBER;
    BEGIN
      DURACION := REC.FECHA_FIN - REC.FECHA_INICIO;

      IF DURACION < 0 THEN
        ERROR_MSG := 'ERROR EN EL PROYECTO: ' || REC.NOMBRE;
        RAISE EXCEPTION_PROYECTO_ERR;
      END IF;

      DBMS_OUTPUT.PUT_LINE('PROYECTO: ' || REC.NOMBRE || ' , DURACION: ' || DURACION || ' DIAS.');

    EXCEPTION
      WHEN EXCEPTION_PROYECTO_ERR THEN
        DBMS_OUTPUT.PUT_LINE(ERROR_MSG);
    END;
  END LOOP;
END;
/
BEGIN
  PR_REPORTE_PROYECTOS;
END;
/

/*Actividad 7: Paquete con funciones reutilizables
Crea un paquete PKG_PROYECTOS que incluya:
Una función que devuelve el total de horas de un empleado en un proyecto específico.
Un procedimiento que recorra todos los proyectos de un empleado y utilice la función anterior para imprimir cada uno con sus horas trabajadas.

*/

CREATE OR REPLACE PACKAGE PKG_PROYECTOS IS

  FUNCTION FN_HORAS_EMPLEADO_PROYECTO(
    P_EMPLEADO_ID IN NUMBER,
    P_PROYECTO_ID IN NUMBER
  ) RETURN NUMBER;

  PROCEDURE PR_REPORTE_HORAS_EMPLEADO(
    P_EMPLEADO_ID IN NUMBER
  );

END PKG_PROYECTOS;
/

--
CREATE OR REPLACE PACKAGE BODY PKG_PROYECTOS IS

  FUNCTION FN_HORAS_EMPLEADO_PROYECTO(
    P_EMPLEADO_ID IN NUMBER,
    P_PROYECTO_ID IN NUMBER
  ) RETURN NUMBER IS
    V_TOTAL_HORAS NUMBER := 0;
  BEGIN
    SELECT NVL(SUM(HORAS_TRABAJADAS), 0)
      INTO V_TOTAL_HORAS
      FROM ASIGNACION
      WHERE EMPLEADO_ID = P_EMPLEADO_ID
        AND PROYECTO_ID = P_PROYECTO_ID;

    RETURN V_TOTAL_HORAS;
  END FN_HORAS_EMPLEADO_PROYECTO;

  PROCEDURE PR_REPORTE_HORAS_EMPLEADO(
    P_EMPLEADO_ID IN NUMBER
  ) IS
  BEGIN
    FOR REC IN (
      SELECT P.ID_PROYECTO, P.NOMBRE
      FROM PROYECTO P
      INNER JOIN ASIGNACION A ON P.ID_PROYECTO = A.PROYECTO_ID
      WHERE A.EMPLEADO_ID = P_EMPLEADO_ID
    ) LOOP
      DBMS_OUTPUT.PUT_LINE(
        'PROYECTO: ' || REC.NOMBRE || ' , HORAS TRABAJADAS: ' || FN_HORAS_EMPLEADO_PROYECTO(P_EMPLEADO_ID, REC.ID_PROYECTO)
      );
    END LOOP;
  END PR_REPORTE_HORAS_EMPLEADO;

END PKG_PROYECTOS;
/

BEGIN
  PKG_PROYECTOS.PR_REPORTE_HORAS_EMPLEADO(2); 
END;
/


