CREATE TABLE TAREA (
    ID NUMBER PRIMARY KEY,
    DESCRIPCION VARCHAR2(255),
    COMPLETADA NUMBER(1),
    CONSTRAINT COMPLETADA_T CHECK (COMPLETADA IN (0, 1))
);


SELECT * FROM TAREA;
INSERT INTO TAREA (ID,DESCRIPCION, COMPLETADA) VALUES (1, 'Comprar alimentos', 0);
INSERT INTO TAREA (ID,DESCRIPCION, COMPLETADA) VALUES (2,'Enviar correo al cliente', 1);
INSERT INTO TAREA (ID,DESCRIPCION, COMPLETADA) VALUES (3,'Revisar reporte financiero', 0);
INSERT INTO TAREA (ID, DESCRIPCION, COMPLETADA) VALUES (4,'Preparar presentación', 1);
INSERT INTO TAREA (ID, DESCRIPCION, COMPLETADA) VALUES (5,'Organizar reunión de equipo', 0);

commit
