CREATE TABLE VEHICULOS (
    ID_VEHICULO NUMBER ,
    MARCA NVARCHAR2(100),
    MODELO NVARCHAR2(100),
    MATRICULA NVARCHAR2(100),
    AÑO_FABRICACION NUMBER,
    CONSTRAINT VEHICULO_PK PRIMARY KEY(ID_VEHICULO)
);

INSERT INTO VEHICULOS  VALUES (1, 'TOYOTA', 'COROLLA', 'ABC123', 2018);

INSERT INTO VEHICULOS VALUES (2, 'HONDA', 'CIVIC', 'DEF456', 2020);

INSERT INTO VEHICULOS  VALUES (3, 'FORD', 'FOCUS', 'GHI789', 2017);

INSERT INTO VEHICULOS  VALUES (4, 'CHEVROLET', 'CRUZE', 'JKL012', 2019);

select * from VEHICULOS;
COMMIT;
DELETE FROM VEHICULOS
WHERE ID_VEHICULO = 0;

ALTER TABLE VEHICULOS RENAME COLUMN AÑO_FABRICACION TO ANO_FABRICACION;
