spring.application.name=EurekaServer

server.port=8761

#configuracion de Eureka
#configuracion del nombre host donde se ejecuta la instancia
eureka.instance.hostname=localhost
#especifica el url del servidor
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#indica que el cliente no debe registrarse en el servidor
eureka.client.register-with-eureka=false
#indica que el cliente no debe obtener el registro de los demas servicios de eureka
eureka.client.fetch-registry=false
#ayuda al servidor contra la perdida de demaciadas instancias en caso de red inestable
eureka.server.enable-self-preservation=true
#exponer todos los endpoint d administracion
management.endpoints.web.exposure.include=*
#mostrar el detalle completo del estado de salud de aplicacion
management.endpoint.health.show-details=always


