spring.application.name=ApiGateway

server.port=9000
#El apiGateway es un componente escencial en la arquitectura de microservicios, que actua como unn punto de entrada unico
#para gestionar todas las solicitudes hacia los microservicios backend. La funcion principal es intermediar o enritar, #y gestionar el trafico de los clientes y los MS
#habliarlos como un eureka client
spring.cloud.service-registry.auto-registration.enabled=true
#configuracion de los servicios a registrar y getionar
#Gestion de Trabiador
#id: Especifica el nombre del microervicio que sera gestionado
spring.cloud.gateway.server.webmvc.routes[0].id=Trabajador
#uri: Especifica la ruta con el puerto del MS a consumir
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8010
#Predicate se refeire a los endpoint de la clase controlador de cada metodo que ira a consumir de ese micoservcio
spring.cloud.gateway.server.webmvc.routes[0].predicates=Path=/T/**

#gestion de pago 

spring.cloud.gateway.server.webmvc.routes[1].id=Pago

spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8012

spring.cloud.gateway.server.webmvc.routes[1].predicates=Path=/P/**

#gestion de empress

spring.cloud.gateway.server.webmvc.routes[2].id=Empresa

spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8014

spring.cloud.gateway.server.webmvc.routes[2].predicates=Path=/E/**

#gestion de contrato

spring.cloud.gateway.server.webmvc.routes[3].id=Contrato

spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8011

spring.cloud.gateway.server.webmvc.routes[3].predicates=Path=/C/**

#gestion de empress

spring.cloud.gateway.server.webmvc.routes[4].id=Departamento

spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8013

spring.cloud.gateway.server.webmvc.routes[4].predicates=Path=/D/**